### ISSUE TITLE
View: Add PMSIpilot to Who Use

### ISSUE THREAD

**Issue by jubianchi** [hoaproject/W3#114]
Hello, as I told Hywan we are using `hoa/ruler` in one of our main projet. Here is our logo:

![pmsipilot-vertical](https://cloud.githubusercontent.com/assets/327237/20052026/3fc2d9c4-a4d2-11e6-93d7-dd73a803f919.png)

Please do not link to our website as we will soon make it look better. It's actually not representative and a bit ugly to be fair.

**Comment by Hywan** [comment]
Hello @jubianchi,

Thanks! Do you have the logo in SVG?

**Comment by jubianchi** [comment]
@Hywan I'll ask the designers if they have it.

**Comment by Hywan** [comment]
Thanks so much!

**Comment by jubianchi** [comment]
@Hywan here it is: https://gist.github.com/jubianchi/18f38271b8e15d58439b862fd7f03416

**Comment by busuttil** [comment]
O_o

**Comment by Hywan** [comment]
Thanks!

**Comment by Hywan** [comment]
@busuttil ?

**Comment by Hywan** [comment]
Deployed on hoa-project.net.
