### ISSUE TITLE
Investigate about the map disappear

### ISSUE THREAD

**Issue by vonglasow** [hoaproject/W3#127]
After 5 click on `+` on the map we have the map which disappear.

Need to investigate about it why this map disappear. See first wrong fix and comments here https://github.com/hoaproject/W3/pull/124#event-984989376

**Comment by Hywan** [comment]
“After 5 clicks” means you have zoomed enough to reach the OSM tiles. And the URL with https seems incorrect :-/.

**Comment by vonglasow** [comment]
Apparently we don't have the level 7 https://static.hoa-project.net/Map/Tiles/

**Comment by vonglasow** [comment]
@Hywan the https is ok but the folders 7 and more are away see url which trying to load resources https://static.hoa-project.net/Map/Tiles/7/65/36.png

**Comment by Hywan** [comment]
We don't have level 7 because from 0 to 6 is from Hoa tiles, and then it's from OSM tiles.

**Comment by Hywan** [comment]
http://c.tile.osm.org/7/64/43.png is valid, but not https://c.tile.osm.org/7/64/43.png, so apparently TLS is not supported.

**Comment by Hywan** [comment]
Apparently, we should use:

```
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'
```

in https://github.com/hoaproject/W3/blob/master/Application/View/Shared/Overlay/Map.xyl. Could you test?

**Comment by vonglasow** [comment]
Ok so after test it works with `openstreetmap` instead of `osm`
