### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by Hywan** [hoaproject/W3#13]
Hello :-),

It would be good to have comments on the documentation. What is the best approach according to your experience?

I am tempted to adopt the approach of [Disqus](http://disqus.com/):
  * comments.hoa-project.net for all the comments,
  * an HTTP (REST-like) API to get, post and delete comments,
  * a very simple backend for moderators (possibly through OAuth + HTTP only),
  * a Javascript loading asynchronously comments and build the HTML output.

Thoughts?

**Comment by Jir4** [comment]
We can use an other third party commenting system, disqus is the most used but not the only one. I think we can review http://intensedebate.com/ or http://web.livefyre.com/apps/comments/ .

**Comment by Hywan** [comment]
Alternative: http://www.discourse.org/

**Comment by Hywan** [comment]
Alternative: http://posativ.org/isso/.

**Comment by camael24** [comment]
Isso sounds good

**Comment by Jir4** [comment]
:+1:
