### ISSUE TITLE
community page issue with avatar of contributor

### ISSUE THREAD

**Issue by Grummfy** [hoaproject/W3#132]
https://hoa-project.net/En/Community.html
![capture du 2017-07-04 20-44-27](https://user-images.githubusercontent.com/668804/27840481-a0cd3bf4-60f9-11e7-89c6-1053d875771d.png)

**Comment by Metalaka** [comment]
Error from Chrome 59 console: 

```
Refused to load the image 'https://github.com/Hywan.png?size=60' because it violates the following Content Security Policy directive: "default-src 'self' *.hoa-project.net *.hoa.io *.github.io *.github.com *.discourse.org *.tile.openstreetmap.org 'unsafe-inline' 'unsafe-eval'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.
…
```

It appear that  **github.com** isn't allowed (without a sub-domain) by the header security rule : `Content-Security-Policy:default-src 'self' *.hoa-project.net *.hoa.io *.github.io *.github.com *.discourse.org *.tile.openstreetmap.org 'unsafe-inline' 'unsafe-eval';`.

Maybe @Pierozi or @Hywan can confirm my idea ?

**Comment by Hywan** [comment]
Fixed! Thanks for the report!

**Comment by Hywan** [comment]
And @Metalaka was correct :+1:.
