### ISSUE TITLE
contributor guide error - missing tools to install or something else

### ISSUE THREAD

**Issue by Grummfy** [hoaproject/W3#133]
Hello,
I follow the contributor guide:
* We have 4 tools to install to contribute to hoa https://hoa-project.net/En/Literature/Contributor/Guide.html#Tools Tools that I have locally
* But when we go to the preparation of patch https://hoa-project.net/Fr/Literature/Contributor/Guide.html#Preparing_a_patch we are suggested to run the following command ```vendor/bin/hoa devtools:cs --dry-run --diff .``` but I got an error

 

> vendor/bin/hoa devtools:cs --dry-run --diff .
> Hoa\Devtools\Bin\Cs::main(): (0) php-cs-fixer binary is not found.
> in /home/jvb/workspace/_perso/hoa/File/vendor/hoa/devtools/Bin/Cs.php at line 112.
> 

test on the hoa/file repository.

So for me here is several stuff to change:
* install php cs fixer as global tools
* add composer depenency for dev to php cs fixer

**Comment by Grummfy** [comment]
by the way, when I install php-cs-fixer globaly, I go errors 
php-cs-fixer --version
PHP CS Fixer 2.3.1 by Fabien Potencier and Dariusz Ruminski (d5257f7)

> $ vendor/bin/hoa devtools:cs --dry-run --diff .
> PHP Fatal error:  Cannot override final method PhpCsFixer\AbstractFixer::fix() in /home/jvb/workspace/_perso/hoa/File/vendor/hoa/devtools/Resource/PHPCSFixer/Fixer/Author.php on line 92
> PHP Stack trace:
> PHP   1. {main}() /home/jvb/bin/bin/php-cs-fixer:0
> PHP   2. Symfony\Component\Console\Application->run() /home/jvb/bin/bin/php-cs-fixer:47
> PHP   3. Symfony\Component\Console\Application->doRun() phar:///home/jvb/bin/bin/php-cs-fixer/vendor/symfony/console/Application.php:121
> PHP   4. Symfony\Component\Console\Application->doRunCommand() phar:///home/jvb/bin/bin/php-cs-fixer/vendor/symfony/console/Application.php:190
> PHP   5. Symfony\Component\Console\Command\Command->run() phar:///home/jvb/bin/bin/php-cs-fixer/vendor/symfony/console/Application.php:826
> PHP   6. PhpCsFixer\Console\Command\FixCommand->execute() phar:///home/jvb/bin/bin/php-cs-fixer/vendor/symfony/console/Command/Command.php:262
> PHP   7. PhpCsFixer\Console\ConfigurationResolver->getReporter() phar:///home/jvb/bin/bin/php-cs-fixer/src/Console/Command/FixCommand.php:144
> PHP   8. PhpCsFixer\Console\ConfigurationResolver->getFormat() phar:///home/jvb/bin/bin/php-cs-fixer/src/Console/ConfigurationResolver.php:405
> PHP   9. PhpCsFixer\Console\ConfigurationResolver->getConfig() phar:///home/jvb/bin/bin/php-cs-fixer/src/Console/ConfigurationResolver.php:560
> PHP  10. include() phar:///home/jvb/bin/bin/php-cs-fixer/src/Console/ConfigurationResolver.php:215
>

**Comment by Hywan** [comment]
Apparently PHP CS Fixer has introduced a regression without changing the versionning. Can you create issues on `hoa/devtools` to address all these issues please?

**Comment by Grummfy** [comment]
=> https://github.com/hoaproject/Devtools/issues/46
