### ISSUE TITLE
Add a button to escape the search mode

### ISSUE THREAD

**Issue by Hywan** [hoaproject/W3#34]
Thanks @roukmoute.

**Comment by osaris** [comment]
+1

**Comment by osaris** [comment]
This is very annoying, there is no way to quit the search mode and go back to the page ?!

**Comment by Hywan** [comment]
@osaris No you can press the escape key, but a button would be bet

**Comment by osaris** [comment]
Doesn't work on chrome.
Le 7 sept. 2015 7:57 AM, "Ivan Enderlin" <notifications@github.com> a
écrit :

**Comment by DisobedientMedia** [comment]
doesn't work on Safari Version 8.0.8 either, thanks. ESC works on Firefox
