### ISSUE TITLE
Present me my language

### ISSUE THREAD

**Issue by osaris** [hoaproject/W3#35]
My language is fr_CH but when I navigate to hoa-project.net I'm presented the english version of the website :-(

**Comment by Hywan** [comment]
@osaris It is based on your browser preferences. Do you have french enabled?

**Comment by osaris** [comment]
for sure !

2015-01-23 22:31 GMT+01:00 Ivan Enderlin <notifications@github.com>:

**Comment by Hywan** [comment]
I also have `fr_CH` and I don't have this issue :-/. Strange. Do you have cache?

**Comment by Hywan** [comment]
@osaris Fixed by https://github.com/hoaproject/W3/commit/58368130a53ef5fccd9787fa943ae05b1a94b45b normally. I did have a cache, not you ;-).

**Comment by osaris** [comment]
Not fixed for me ...

**Comment by Hywan** [comment]
@osaris Cache?

**Comment by Hywan** [comment]
@osaris I tried with cURL to avoid the caching.

**Comment by osaris** [comment]
Right, sorry !

2015-01-26 10:59 GMT+01:00 Ivan Enderlin <notifications@github.com>:
