### ISSUE TITLE
Add quick link in Hackbook

### ISSUE THREAD

**Issue by camael24** [hoaproject/W3#41]
I suggest to add an quick link when we focus an section title, to make esay to share this link
In this hackbook http://hoa-project.net/Fr/Literature/Hack/Console.html, i scroll to the section 
http://hoa-project.net/Fr/Literature/Hack/Console.html#Detect_the_type_of_pipes

When i focus the title **Détecter le type des pipes**, make it clickable to have the link

**Comment by Grummfy** [comment]
I agree this is very helpfull!

**Comment by Jir4** [comment]
I'll prefer a small "share image" on the right of the title which appear when the cursor is on it, it does'nt modify the behavior of the title.

**Comment by Hywan** [comment]
@Jir4 +1, like Github does.

**Comment by camael24** [comment]
@Jir4 +1 its good too :)
