### ISSUE TITLE
Error page

### ISSUE THREAD

**Issue by Grummfy** [hoaproject/W3#47]
Example of people doing something strange :
http://hoa-project.net/Fr/Literature/Hack/Nawak.html
Error I get:

    string(80) "File hoa://Library/Nawak/Documentation/Fr/Index.xyl is not found, cannot use it."

**Comment by Hywan** [comment]
Yup, known bug…

**Comment by Hywan** [comment]
Related to https://github.com/hoaproject/W3/issues/33.
