### ISSUE TITLE
invisible char near title

### ISSUE THREAD

**Issue by Grummfy** [hoaproject/W3#50]
Near the title in the hack book there is a messing char (css error or font not imported?)
![capture du 2015-04-03 14 04 36](https://cloud.githubusercontent.com/assets/668804/6981930/9fdff40c-da0a-11e4-8449-356cea08cbfe.png)

**Comment by Jir4** [comment]
It's related with #48, you should see a link char : http://www.fileformat.info/info/unicode/char/1f517/index.htm

**Comment by Bhoat** [comment]
Do you have Emoji?

**Comment by Hywan** [comment]
@Grummfy It's revealed only on `:hover` right?

**Comment by Grummfy** [comment]
@Jir4 : I see the char on the given webpage but not on hack book
@Hywan  : on hover, right!.

**Comment by Hywan** [comment]
@Grummfy What browser and OS do you have?

**Comment by Grummfy** [comment]
I'm on ubuntu 14.04 LTS. I have tested with chrome, chromium and firefox.

**Comment by Jir4** [comment]
@Grummfy Did you see the char on this page ? http://www.fileformat.info/info/unicode/char/1f517/browsertest.htm

**Comment by Grummfy** [comment]
nop, and like I say on irc : not under another linux or windows 8.1

**Comment by Hywan** [comment]
@Grummfy And here: http://graphemica.com/%F0%9F%94%97?

**Comment by Grummfy** [comment]
works

**Comment by Hywan** [comment]
Ok so we have to find a font to print emoji. We have this one: http://emojisymbols.com/ (format is WOFF).

**Comment by Hywan** [comment]
Or Symbola (for Linux): http://users.teilar.gr/~g1951d/

**Comment by Hywan** [comment]
Or Android font: https://github.com/android/platform_frameworks_base/tree/master/data/fonts.

**Comment by Grummfy** [comment]
fontawsome, glyficon, ....

**Comment by Hywan** [comment]
Fixed by http://git.hoa-project.net/Static.git/commit/?id=4b5af385742e1966556a4223455634e5e5227357:

![screen shot 2015-04-09 at 15 42 02](https://cloud.githubusercontent.com/assets/946104/7067923/20fbc8d6-decf-11e4-950d-269454c02ce9.png)

(update your cache)

**Comment by Hywan** [comment]
@Grummfy font awesome and glyicons are not Emoji, they are special fonts. Here we use registered and standard characters.

**Comment by Grummfy** [comment]
perfect. thanks
