### ISSUE TITLE
Better promote Rush Release

### ISSUE THREAD

**Issue by Hywan** [hoaproject/W3#55]
Based on this http://www.reddit.com/r/PHP/comments/3905hj/hoa_has_adopted_psr1_and_psr2/, we must do something.

Thoughts @hoaproject/hoackers?

**Comment by Pierozi** [comment]
Maybe we should put a few words about Rush Release in Installation section of Readme.md for every repository, like you recently open an update on #19

**Comment by Hywan** [comment]
Hmm, good idea too!

**Comment by Hywan** [comment]
@Pierozi You meant https://github.com/hoaproject/Central/issues/19 ;-)

**Comment by Hywan** [comment]
Closing in favor of https://github.com/hoaproject/Central/issues/19.
