### ISSUE TITLE
No scrollbar on Chrome

### ISSUE THREAD

**Issue by osaris** [hoaproject/W3#68]
For example on the http://hoa-project.net/En/Literature/Hack/Test.html page there is no scrollbar when using google chrome. Scrolling is ok but you don't know where you are on the page :-(

Works fine on Safari and Firefox.

**Comment by Hywan** [comment]
This seems to be a bug with Google Chrome. Can you reproduce with another version of the software?

**Comment by Metalaka** [comment]
Works on Chrome current version (45).

**Comment by Hywan** [comment]
So this is a bug with Chrome. I can't print scrollbar for him ;-).

**Comment by osaris** [comment]
@Metalaka I'm running Chrome 45.0.2454.85 (64-bit)

**Comment by Metalaka** [comment]
Running the same snapshot on Win64, and I can see the default Chrome scroll bar like here on GitHub.
Did you try on an other computer ?

**Comment by osaris** [comment]
I restarted Chrome and it works fine now, bad habit to restart my browser
only every few weeks ... :-)

2015-09-07 18:23 GMT+02:00 Metalaka <notifications@github.com>:

**Comment by Hywan** [comment]
;-)
