### ISSUE TITLE
download.hoa-project.net is not up to date

### ISSUE THREAD

**Issue by Jir4** [hoaproject/W3#87]
Hi,

In the [documentation](http://hoa-project.net/En/Source.html), we propose http://download.hoa-project.net/ as a mirror to download archives of our libs. But all this archives are old. We need to choose between in one hand keep this possibility and maintain this mirror or down it in another hand.

It's not the only thing we have to keep in mind, for exemple the [API doc](http://api.hoa-project.net/) is not up to date too.

Maybe it's possible to automate the whole process with a hook on the github tag event ?

**Comment by Hywan** [comment]
@Jir4 We must remove the `download` sub-domain. Can you make a PR to update the website? We will update the nginx configuration on our side.

About the API documentation, yes, we must automate it.
